# general settings
name: train_BPOSR_SRx4
model_type: SRModel
scale: 4
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: odisr_train
    type: OmniImageDataset
    dataroot_gt: ./Dataset/lau_dataset_clean/odisr/training/HR
    dataroot_lq: ./Dataset/lau_dataset_clean/odisr/training/LR/X4
    meta_info_file: ~
    filename_tmpl: '{}'
    io_backend:
      type: disk

    use_roll : true
    use_hflip: true
    use_vflip: true
    use_rot: false
    gt_h: 1024
    gt_w: 2048

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: odisr_test
    type: OmniImageDataset
    dataroot_gt: ./Dataset/lau_dataset_clean/odisr/testing/HR
    dataroot_lq: ./Dataset/lau_dataset_clean/odisr/testing/LR/X4
    io_backend:
      type: disk
    gt_h: 1024
    gt_w: 2048

# network structures
network_g:
  type: BPOSR
  upscale: 4
  in_chans: 3
  img_size: [256,512]
  cmp_window_size: [8,8]
  erp_window_size: [4,16]
  roll_r: 3
  img_range: 1.
  depths: [6,6,6,6]
  embed_dim: 60
  num_heads: [6,6,6,6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5000
  save_img: false

  metrics:
    psnr_ws: # metric name, can be arbitrary
      type: calculate_psnr_ws
      crop_border: 4
      test_y_channel: true

    ssim_ws: # metric name, can be arbitrary
      type: calculate_ssim_ws
      crop_border: 4
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500